### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maacl** [Bogdanp/Franz#1]
Great that you are making the code available, but please note that if you want users to be able to "change and build it for themselves" in a legally sound way, you will need to subject the code to a license permitting such actions.

**Comment by Bogdanp** [comment]
Thanks for the input! Back when I made [Remember] source available, there was some discussion on this topic as well, though I can't find it right now. I'll try to post it here if I can find it later, but my view is the information in the README is sufficiently clear about what someone may do with the source code. 

[Remember]: https://github.com/bogdanp/remember
